# Generated by Django 3.2.15 on 2022-08-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PdfRipper', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='Pic',
        ),
    ]
