# Generated by Django 3.2.15 on 2022-08-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PdfRipper', '0003_delete_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='FileName')),
                ('imagefile', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
